### ISSUE TITLE
Some comp tests are failing due to JSBML flattening

### ISSUE THREAD

**Issue by matthiaskoenig** [draeger-lab/SBSCL#36]
Currently some of the comp tests are failing due to problems with flattening. Issue is reported here:
https://github.com/sbmlteam/jsbml/issues/213

**Comment by shalinshah1993** [comment]
Seems like this issue is fixed. Shall we close it?

**Comment by hemilpanchiwala** [comment]
@shalinshah1993, this issue is of JSBML which isn't solved till now.  Currently, we have just skipped these tests. And, the pre-gsoc label should not be given to this issue as it's done after GSoC start.

**Comment by draeger** [comment]
Is the issue already filed in JSBML's [tracker](https://github.com/sbmlteam/jsbml/issues)?
* If so, could you please provide the link to the item?
* If not, could you please create one and then provide the link?
Thanks!

**Comment by hemilpanchiwala** [comment]
> Is the issue already filed in JSBML's [tracker](https://github.com/sbmlteam/jsbml/issues)?
> 
> * If so, could you please provide the link to the item?
> * If not, could you please create one and then provide the link?
> 
> Thanks!

Its provided by @matthiaskoenig in the description of the issue.

**Comment by dyrpsf** [comment]
Hi team! 
I tracked down the root cause of this flattening failure. The bug was actually upstream in JSBML's `CompFlatteningConverter` ([JSBML Issue #213](https://github.com/sbmlteam/jsbml/issues/213)). I just submitted a [PR #297](https://github.com/sbmlteam/jsbml/pull/297) to JSBML with the fix. Once that is merged and the JSBML dependency updates, these SBSCL tests will start passing again!

**Comment by draeger** [comment]
I merged @dyrpsf's fix. This issue can be closed upon incorporation of the next JSBML version.
